apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: whopkcore 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: whopkcore 
    spec:
      containers:
        - name: whopkcore 
          image: randomcontainerregistry.azurecr.io/whopkcore
          ports:
          - containerPort: 80